#!/usr/bin/env python
"""script file for sp_file_explorer"""
from tkinter import Tk
import logging

from spfe.sp_file_explorer import FileExplorerGUI

if __name__ == "__main__":
    logging.basicConfig(format="%(asctime)s-%(levelname)s: %(message)s",
                        level=logging.INFO,
                        handlers=[logging.FileHandler("sp_file_explorer.log"),
                                  logging.StreamHandler()])
    ROOT = Tk()
    GUI = FileExplorerGUI(ROOT, logging.getLogger())
    ROOT.mainloop()
